### ISSUE TITLE
Convert to frozen graph (tensorflow saved format to tensorflow frozen graph)

### ISSUE THREAD

**Issue by chansoopark98** [chansoopark98/NodeJS-based-DeepLearning#2]
Ah, I see.
In the case of tf.loadGraphModel, a static graph type model is loaded.
https://github.com/chansoopark98/Tensorflow-Keras-Object-Detection/blob/main/convert_frozen_graph.py
Please refer to my repository.
The method is to build a model trained with TensorFlow or Keras, load and apply weights.
Running that code creates a frozen graph with the specified path.

When the conversion is complete, convert it to the tensorflowjs_converter ./checkpoints/new_tfjs_frozen/frozen_graph.pb ./checkpoints/converted_tfjs/ --input_format=tf_frozen_model --output_node_names='Identity' --quantize_float16 command.

Once the transformation is complete, you can load the model from tfjs using tf.loadGraphModel.
Please try it and contact us if any errors occur.

_Originally posted by @chansoopark98 in https://github.com/chansoopark98/NodeJS-based-DeepLearning/issues/1#issuecomment-1207634200_

**Comment by mtrucc** [comment]
Thank you very much for your reply.I trained the model according to this tutorial, but it doesn't work, seems to be too new

[Custom object detection in the browser using TensorFlow.js](https://blog.tensorflow.org/2021/01/custom-object-detection-in-browser.html)
[Training a model for custom object detection (TF 2.x) on Google Colab](https://techzizou.com/training-an-ssd-model-for-a-custom-object-using-tensorflow-2-x/)
After I load the model in this example, I got some errors

https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd

Error：https://github.com/tensorflow/tfjs/issues/4638

The exported model after training does not look like the Frozen Model, I plan to retrain and generate a Model for js

**Comment by chansoopark98** [comment]
You must convert from TensorFlow to Frozen Graph first. Build a TensorFlow model and load the weights. Did this work work? If this is done, you can convert it to something like https://github.com/chansoopark98/Tensorflow-Keras-Object-Detection/blob/main/convert_frozen_graph.py.

**Comment by mtrucc** [comment]
> You must convert from TensorFlow to Frozen Graph first. Build a TensorFlow model and load the weights. Did this work work? If this is done, you can convert it to something like https://github.com/chansoopark98/Tensorflow-Keras-Object-Detection/blob/main/convert_frozen_graph.py.

My steps are not the same as yours

Use `model_main_tf2.py` for training
https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py

Use `exporter_main_v2.py` for export the model. We’re going to convert the training checkpoints to a protobuf (pb) file. This file is going to have the graph definition and the weights of the model.
https://github.com/tensorflow/models/blob/master/research/object_detection/exporter_main_v2.py

```
├── inference-graph
│ ├── saved_model
│ │ ├── assets
│ │ ├── saved_model.pb
│ │ ├── variables
│ │ ├── variables.data-00000-of-00001
│ │ └── variables.index
```

I'm trying to convert from TensorFlow to Frozen Graph.Maybe my training operations are correct, but my transformations are incorrect

**Comment by chansoopark98** [comment]
Okay. Would you like to try this first?

We write the water code and send it to you.

1. Load the TensorFlow .pb file into the TensorFlow model.
2. After loading the model, convert it to a frozen graph.

I used tf-keras (keras model) by converting it into a frozen graph.



# Import library
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

# set .pb file path
export_dir = 'your protobuf(.pb) file dir'

# Load model
model = tf.saved_model.load(export_dir)

 #path of the directory where you want to save your model
frozen_out_path = './checkpoints/output_frozen_graph_model'
# name of the .pb file
frozen_graph_filename = "frozen_graph"
# Convert Keras model to ConcreteFunction
full_model = tf.function(lambda x: model(x))
full_model = full_model.get_concrete_function(
    tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))
# Get frozen ConcreteFunction
frozen_func = convert_variables_to_constants_v2(full_model)
frozen_func.graph.as_graph_def()
layers = [op.name for op in frozen_func.graph.get_operations()]
print("-" * 60)
print("Frozen model layers: ")
for layer in layers:
   print(layer)
print("-" * 60)
print("Frozen model inputs: ")
print(frozen_func.inputs)
print("Frozen model outputs: ")
print(frozen_func.outputs)
# Save frozen graph to disk
tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                logdir=frozen_out_path,
                name=f"{frozen_graph_filename}.pb",
                as_text=False)
# Save its text representation
tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                logdir=frozen_out_path,
                name=f"{frozen_graph_filename}.pbtxt",
                as_text=True)

**Comment by mtrucc** [comment]
After research, I found that our models are inconsistent
I use save model
As noted https://github.com/tensorflow/models/issues/8858#issuecomment-658348127 frozen graphs are not supported in TF2.
I did not transform the model, I reanalyzed the output data and wrote a new js function to process it

**Comment by chansoopark98** [comment]
Well, some can. But that's not the case in my case.
The deep learning model I'm working on works on tensorflow 2.9.1.
In the case of a general model, it is possible to use it by converting it to a keras model or tensorflow saved model, but it was confirmed that some functions and logic of post-processing do not work in tensorflowjs_converter. To solve this method, a detection model and post processing are combined to make a single keras model, and then converted into a frozen graph. Finally, the converted frozen graph is converted to a tfjs model.

**Comment by mtrucc** [comment]
> Well, some can. But that's not the case in my case. The deep learning model I'm working on works on tensorflow 2.9.1. In the case of a general model, it is possible to use it by converting it to a keras model or tensorflow saved model, but it was confirmed that some functions and logic of post-processing do not work in tensorflowjs_converter. To solve this method, a detection model and post processing are combined to make a single keras model, and then converted into a frozen graph. Finally, the converted frozen graph is converted to a tfjs model.

Yes, you can use [Object Detection API TensorFlow 2](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md) get new save  model(tf2)

Colab code [Fine-tune a pre-trained detector in eager mode on custom data](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb)

Technical details for advanced users(old, for tf1.x)
Python [export_inference_graph.py](https://github.com/tensorflow/models/blob/master/research/object_detection/export_inference_graph.py) 
Model [SSD MobileNet V1 FPN 640x640](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v1_fpn_640x640_coco17_tpu-8.tar.gz)

But I don't use the above script, I use [model_main_tf2.py](https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py) and [SSD MobileNet v2 320x320](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz) Model

Then I found that most of the demos on the Internet and the official demos are invalid. I thought there was something wrong with my model.

In fact, there is no problem with the model. The problem is that the demo and online projects have not been updated. They are all 2 years ago. If I consider downgrading the TF version and the tfjs version and re-converting, I should be able to get the correct model.

**Comment by chansoopark98** [comment]
Hello, if you want to run ssd based detection code in .js, here is my
repository.
I'm currently working on making object detection in javascript possible at
about 10fps or less.
Can you provide a demo version?
I hope it helps.

2022년 8월 10일 (수) 오후 12:39, mtrucc ***@***.***>님이 작성:

**Comment by chansoopark98** [comment]
https://github.com/chansoopark98/Tensorflow-Keras-Object-Detection

2022년 8월 10일 (수) 오후 12:55, 박찬수 ***@***.***>님이 작성:

**Comment by chansoopark98** [comment]
Hello, if you want to run ssd based detection code in .js, here is my repository.
I'm currently working on making object detection in javascript possible at about 10fps or less.
I'm editing the readme right now so that I can provide a working demo and a demo version.
I hope this helps you.

https://github.com/chansoopark98/Tensorflow-Keras-Object-Detection
